export const api = {
    getMovies() {
        return new Promise((resolve) => {
            resolve({
                data: [{
                    id: 962,
                    title: 'The Gold Rush',
                    tagline: "The World's Greatest Laughing Picture!",
                    vote_average: 7.8,
                    vote_count: 411,
                    release_date: '1925-06-25',
                    poster_path: 'https://image.tmdb.org/t/p/w500/eQRFo1qwRREYwj47Yoe1PisgOle.jpg',
                    overview: 'A lone prospector ventures into Alaska looking for gold.',
                    budget: 923000,
                    revenue: 2500000,
                    genres: ['Adventure', 'Comedy', 'Drama'],
                    runtime: 95,
                }, {
                    id: 19,
                    title: 'Metropolis',
                    tagline: 'There can be no understanding between the hands and the brain unless the heart acts.',
                    vote_average: 8.1,
                    vote_count: 837,
                    release_date: '1927-01-10',
                    poster_path: 'https://image.tmdb.org/t/p/w500/qriaeUUwdmlgethK3aSAx68mG05.jpg',
                    overview: 'In a futuristic city sharply divided between the working class and the city planners.',
                    budget: 92620000,
                    revenue: 650422,
                    genres: ['Drama', 'Science Fiction'],
                    runtime: 153,
                }, {
                    id: 143,
                    title: 'All Quiet on the Western Front',
                    tagline: 'They left for war as boys never to return as men.',
                    vote_average: 7.6,
                    vote_count: 216,
                    release_date: '1930-04-29',
                    poster_path: 'https://image.tmdb.org/t/p/w500/9gn5ce3B2vOpk9pOGeUjmFecIo5.jpg',
                    overview: 'A young soldier faces profound disillusionment in the soul-destroying.',
                    budget: 1250000,
                    revenue: 0,
                    genres: ['Drama', 'War'],
                    runtime: 133,
                }, {
                    id: 901,
                    title: 'City Lights',
                    tagline: 'True Blind Love',
                    vote_average: 8.2,
                    vote_count: 581,
                    release_date: '1931-01-30',
                    poster_path: 'https://image.tmdb.org/t/p/w500/bXNvzjULc9jrOVhGfjcc64uKZmZ.jpg',
                    overview: 'City Lights is the first silent film that Charlie Chaplin.',
                    budget: 1500000,
                    revenue: 19181,
                    genres: ['Comedy', 'Drama', 'Romance'],
                    runtime: 87,
                }, {
                    id: 138,
                    title: 'Dracula',
                    tagline: 'The story of the strangest passion the world has ever known!',
                    vote_average: 7.2,
                    vote_count: 329,
                    release_date: '1931-02-12',
                    poster_path: 'https://image.tmdb.org/t/p/w500/hA9kQrIwDHJKl1pt8GpJdDnBzim.jpg',
                    overview: 'The legend of vampire Count Dracula begins here with this original 1931 Dracula.',
                    budget: 355000,
                    revenue: 0,
                    genres: ['Horror'],
                    runtime: 72,
                }, {
                    id: 3035,
                    title: 'Frankenstein',
                    tagline: 'The man who made a monster.',
                    vote_average: 7.4,
                    vote_count: 395,
                    release_date: '1931-11-21',
                    poster_path: 'https://image.tmdb.org/t/p/w500/wB58wlBAr6484Wm6VyFDqSD8VOJ.jpg',
                    overview: 'Henry Frankenstein.',
                    budget: 291000,
                    revenue: 12000000,
                    genres: ['Drama', 'Horror', 'Science Fiction'],
                    runtime: 71,
                }, {
                    id: 15849,
                    title: 'The Mummy',
                    tagline: 'It comes to life!',
                    vote_average: 6.8,
                    vote_count: 155,
                    release_date: '1932-12-22',
                    poster_path: 'https://image.tmdb.org/t/p/w500/vSKpbZVvzqQcw6htiyEinbCY9vq.jpg',
                    overview: 'the soul of his lover.',
                    budget: 196000,
                    revenue: 0,
                    genres: ['Horror'],
                    runtime: 73,
                }, {
                    id: 244,
                    title: 'King Kong',
                    tagline: "A Monster of Creation's Dawn Breaks Loose in Our World Today!",
                    vote_average: 7.7,
                    vote_count: 448,
                    release_date: '1933-04-07',
                    poster_path: 'https://image.tmdb.org/t/p/w500/vXInYahVp31uL8wZORckaoHq565.jpg',
                    overview: 'King Kong films.',
                    budget: 672000,
                    revenue: 10000000,
                    genres: ['Action', 'Adventure', 'Drama', 'Horror'],
                    runtime: 100,
                }, {
                    id: 3078,
                    title: 'It Happened One Night',
                    tagline: 'TOGETHER... for the first time',
                    vote_average: 7.7,
                    vote_count: 356,
                    release_date: '1934-02-22',
                    poster_path: 'https://image.tmdb.org/t/p/w500/k63JqnFvkIGWGhjsqRiksZw2OSs.jpg',
                    overview: 'newspaper story!',
                    budget: 325000,
                    revenue: 4500000,
                    genres: ['Comedy', 'Romance'],
                    runtime: 105,
                }, {
                    id: 260,
                    title: 'The 39 Steps',
                    tagline: 'Handcuffed to the girl who double-crossed him',
                    vote_average: 7.5,
                    vote_count: 274,
                    release_date: '1935-06-01',
                    poster_path: 'https://image.tmdb.org/t/p/w500/9v283GWj9a0AC8wwC4zriNqY1lZ.jpg',
                    overview: 'mission.',
                    budget: 0,
                    revenue: 0,
                    genres: ['Action', 'Thriller', 'Mystery'],
                    runtime: 86,
                },
                ],
                total: 3000,
                offset: 0,
                limit: 10,
            });
        });
    },
};
